#!/usr/bin/env python3
"""Generate requirements.txt based on NVIDIA driver version."""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS_DIR = ROOT / "requirements"

# Driver major version -> PyTorch wheel variant
# cu128 is deliberately excluded from auto-selection because its wheels require
# very recent host libraries; it can still be forced with --variant cu128.
DRIVER_MAP = [
    (525, "cu124"),   # CUDA 12.4 (broad driver support, stable)
    (520, "cu121"),   # CUDA 12.1
    (450, "cu118"),   # CUDA 11.8
]


def detect_driver_version() -> str | None:
    """Return driver version string from nvidia-smi, or None if not available."""
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        return out.strip().splitlines()[0]
    except Exception:
        return None


def parse_driver_major(version_str: str) -> int | None:
    """Extract the major version number from a driver string like '535.104.05'."""
    m = re.match(r"(\d+)\.", version_str)
    return int(m.group(1)) if m else None


def select_variant(driver_major: int | None) -> str:
    """Select PyTorch variant based on driver major version."""
    if driver_major is None:
        return "cpu"
    for threshold, variant in DRIVER_MAP:
        if driver_major >= threshold:
            return variant
    return "cpu"


def generate(output_path: str, variant: str | None = None) -> None:
    """Merge base + torch variant into a single requirements.txt."""
    if variant is None:
        driver_version = detect_driver_version()
        if driver_version:
            major = parse_driver_major(driver_version)
            variant = select_variant(major)
            print(f"Detected NVIDIA driver {driver_version} -> using {variant}")
        else:
            variant = "cpu"
            print("No NVIDIA driver detected -> using cpu")
    else:
        print(f"Using requested variant: {variant}")

    base_file = REQUIREMENTS_DIR / "base.txt"
    torch_file = REQUIREMENTS_DIR / f"torch-{variant}.txt"

    if not base_file.exists():
        sys.exit(f"Missing {base_file}")
    if not torch_file.exists():
        supported = ", ".join(sorted(set([v for _, v in DRIVER_MAP] + ["cpu", "cu128"])))
        sys.exit(f"Variant file not found: {torch_file}. Supported variants: {supported}")

    parts = [
        f"# Auto-generated by {Path(__file__).name} (variant: {variant})\n",
        torch_file.read_text().strip() + "\n",
        base_file.read_text().strip() + "\n",
    ]

    out = Path(output_path)
    out.write_text("".join(parts))
    print(f"Wrote {out.resolve()}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate requirements.txt matched to the host GPU driver."
    )
    parser.add_argument(
        "--variant",
        choices=["cpu", "cu118", "cu121", "cu124", "cu128"],
        help="Force a specific PyTorch variant instead of auto-detecting",
    )
    parser.add_argument(
        "-o", "--output", default="requirements.txt", help="Output file path"
    )
    args = parser.parse_args()
    generate(args.output, variant=args.variant)


if __name__ == "__main__":
    main()
